### PR TITLE
variables to create server certs; require static IP; includes example

### PR DESCRIPTION
**Pull request by drnic**
This PR generates TLS certificates for the Docker Registry.

It assumes BOSH DNS is enabled, and the default manifest exposes `docker-registry.bosh` hostname.

An operator is provided to also support a static IP.

### CODE REVIEW

**Comment by jhunt** [comment]
@jordanbcooper would be the person to ask; I believe he is the primary user these days.

I mostly just deploy my docker registries as kubernetes CRs these days, without (directly) using BOSH.

**Comment by drnic** [comment]
@jhunt ok thanks; I came back to this bosh release whilst developing an airgapped version of k3s.io boshrelease, which wants a local private registry to install and serve its airgapped images.

**Comment by drnic** [comment]
current status: investigating BOSH DNS as the default, so I can get rid of the static IP requirement.

**Comment by drnic** [comment]
@jordanbcooper I've updated the PR to default to BOSH DNS `docker-registry.bosh`, and an operator to support static IPs.

**Comment by drnic** [comment]
I'm going to merge. The PR doesn't change the BOSH release; just the out of date docs + manifests.

**Pull request merged**
