### PR TITLE
Update docker distribution from 2.6.2 to 2.7.0 and golang from 1.7.3 to 1.11

### PR DESCRIPTION
**Pull request by bradorchard**
Release Notes: https://github.com/docker/distribution/tree/v2.7.0
Tarball: https://github.com/docker/distribution/archive/v2.7.0.tar.gz

### CODE REVIEW

**Comment by bradorchard** [comment]
Hi - can confirm I've tested this locally and it's all working as expected

**Comment by bradorchard** [comment]
Hi, I've already tested this locally and it's all working as expected. Our dev release was running go 1.11 and distribution 2.7.0 on the trustee stem cell with no issues. 

During initial testing with the dev release, we found an issue with the older version of golang and that's why we updated it to 1.11.

**Comment by kitsirota** [comment]
@jhunt Could you merge this to master so we can do another round of testing using the blobs you uploaded?

**Comment by jhunt** [comment]
Uploading blobs currently.  Expect a force-push to get new config/blobs.yml

**Pull request merged**
